### ISSUE TITLE
Rebar3 Auto Cant find app file

### ISSUE THREAD

**Issue by byaruhaf** [vans163/rebar3_auto#2]
hello
i have problem my erlang application fails to boot when i use rebar3 auto plugin
i get the error below:

===> Failed to boot limko for reason {"no such file or directory",
                                             "limko.app"}

Yet the limko.app file is in the ebin folder, is there any way to fix this?

mead a recording of  the build process 
https://asciinema.org/a/27317

**Comment by tsloughter** [comment]
Are you using the version from hex? I hadn't published the fix for this to hex yet. If you update your plugin now to 0.3.0 it should work.

**Comment by byaruhaf** [comment]
using 0.3.0

λ VIDIA limko → rebar3 auto
===> Fetching rebar3_auto ({pkg,<<"rebar3_auto">>,<<"0.3.0">>})

But still same error see out put below

https://gist.github.com/byaruhaf/bcb8b361528a0f7bd4b5

**Comment by tsloughter** [comment]
Well damn... It resolved the issue for me. Hm, actually, it doesn't seem to be using 0.3.0 for some reason. There should now always be `===> Compiling limko` before it tries to start the shell, the fix was to making `compile` a dep of `auto`.

**Comment by byaruhaf** [comment]
Just an update

when the plugin is in the global rebar3 configuration file

```
~/.config/rebar3/rebar.config:
```

**_rebar3 auto**_ fails to find the app file.
When the plugin is in the project rebar.config file

```
/home/byaruhaf/projects/erlang/limko/rebar.config
```

**_rebar3 auto**_ works perfectly 

i had added it to the global rebar3 configuration file to be able to use it on any projects.

**Comment by tsloughter** [comment]
Ah, are you sure the global one is upgraded to 0.3.0 and not just the local one? To upgrade a global plugin you have to do: `rebar3 as global plugins upgrade rebar3_auto`

**Comment by byaruhaf** [comment]
Thanks that fixed it, global one was not updated to 0.3.0 all is now okay

```
λ VIDIA otto → λ git master* → rebar3 as global plugins upgrade rebar3_auto
===> No entry for profile global in config.
===> Upgrading rebar3_auto ({pkg,<<"rebar3_auto">>,<<"0.3.0">>})
===> Version cached at /home/byaruhaf/.cache/rebar3/hex/default/packages/rebar3_auto-0.3.0.tar is up to date, reusing it
===> No upgrade needed for enotify
```

**Comment by tsloughter** [comment]
Woo, great! Sorry for the confusion with `global`. I might need to figure out a better way to handle that.

**Comment by byaruhaf** [comment]
No problem, was looking to replace **_sync**_ so this now works for me. Thanks for your assistance and time on this issue.
