### ISSUE TITLE
Modules not recompiled with rebar3 auto

### ISSUE THREAD

**Issue by schnef** [vans163/rebar3_auto#20]
I love the rebar3 auto plug-in, but it doesn't work anymore, probably after an update of Erlang recently but I am not sure.
On saving a file, the shell displays `Verifying dependencies...` but the module doesn't get compiled. The project I am working on is structured as a regular (rebar3) app. 
Do you have any suggestions on getting things working properly again?

Thanks, 
Frans

Version info:
rebar 3.12.0 on Erlang/OTP 22 Erts 10.4.4
Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

**Comment by vans163** [comment]
Let me take a look..

**Comment by schnef** [comment]
Somewhere in my code, I call file:set_cwd/1 to /tmp. This is what the problem did cause.
