### ISSUE TITLE
Empty module lol in published hex package 0.3.3

### ISSUE THREAD

**Issue by ghost** [vans163/rebar3_auto#22]
I'm not sure what this is doing there but it's in the currently published hex package for 03.3. It's empty so perhaps it was mistakenly there when publishing. lol

**Comment by vans163** [comment]
I think I was testing events proccing off files and made a file called `lol`. It seems HEX publisher deploys all the files in the repo, not just the ones under source control tracking, so it got in with the hex publish.

Good catch. Il probably remove it in the next release, I do not think it warrants a re-release..
