### ISSUE TITLE
Error description if inotify-tools isn't installed in a linux pc

### ISSUE THREAD

**Issue by unbalancedparentheses** [vans163/rebar3_auto#4]
If inotify-tools are not installed this is the error you get:
`-m: inotifywait: command not found`

Screenshot:
![screenshot from 2016-02-04 17-25-05](https://cloud.githubusercontent.com/assets/569014/12828544/4075e976-cb64-11e5-9899-9c367d8b7280.png)

rebar3 auto is a great replacement for sync. However since sync is a 100% erlang app that doesn't depend on anything else,  Erlang newcomers that replace sync by rebar3_auto might take some time to relate that error with rebar3_auto. That is why I think a better error should be printed out if inotifywait command is not found.

I think that if inotifywait is not found, then it should ask the user to install it. Also it would be a good idea to add it as a dependency in the readme of rebar3_auto and the documentation of rebar3 for linux users.

Let me know what you think and I would be glad to implement it or to help.

**Comment by tsloughter** [comment]
Forgot about this. It definitely would be nice if it had a fallback.

**Comment by vans163** [comment]
Just bumped into this issue.

I added inotify for linux to SCV. https://github.com/vans163/scv/blob/master/c_src/inotify.c  But since rebar3 does this perhaps merging native inotify support would be good? It wont work on FreeBSD (which does not have inotify but Kqueue).

**Comment by fenollp** [comment]
Bumped into this as well.
Didn't know that https://github.com/rustyio/sync does not have external deps. This should probably be the solution here.
In the meanwhile a better error message + mention dependency in the REAMDE are great ideas!

**Comment by vans163** [comment]
This is listed as a prerequisite in the readme now.
