### ISSUE TITLE
Only compile once and never compile again

### ISSUE THREAD

**Issue by goofansu** [vans163/rebar3_auto#5]
OSX 10.11.4

```
===> This feature is experimental and may be modified or removed at any time.
Verifying dependencies...
Compiling server
```

rebar.config

```
%% -*- mode: erlang; -*-

{erl_opts,
 [debug_info,
  {parse_transform, lager_transform},
  {i, "./_build/default/plugins/gpb/include"}
 ]}.

{deps,
 [{lager, {git, "git://github.com/basho/lager.git", {tag, "3.1.0"}}},
  {ranch, {git, "git://github.com/ninenines/ranch.git", {tag, "1.2.1"}}},
  {eredis, {git, "git://github.com/wooga/eredis.git", {tag, "v1.0.8"}}},
  {syn, {git, "git://github.com/ostinelli/syn.git", {tag, "1.3.0"}}}
 ]}.

{plugins,
 [rebar3_auto,
  rebar3_gpb_plugin
 ]}.

{provider_hooks,
 [{pre,
   [{compile, {protobuf, compile}},
    {clean, {protobuf, clean}}
   ]}
 ]}.

{gpb_opts,
 [{module_name_suffix, "_pb"},
  strings_as_binaries,
  type_specs,
  maps
 ]}.

{relx,
 [{release, {'server', "0.0.1"},
   [server]},
  {dev_mode, true},
  {include_erts, false},
  {extended_start_script, true}
 ]}.
```

**Comment by radupopescu** [comment]
I am also seeing this on my Macbook pro running OS X 10.11.5. I haven't yet tried this plugin on a Linux machine.

**Comment by tsloughter** [comment]
Yea, this is broken and i don't know why and don't have the time to figure it out for a while :(

**Comment by ziyouchutuwenwu** [comment]
yes, i have the same issue, mac 10.11.5, erlang otp r19.0.2

**Comment by zyuyou** [comment]
Same on Ubuntu 16.04, otp 17.5.

**Comment by hstcscolor** [comment]
Same on Ubuntu

**Comment by vans163** [comment]
As MononcQc explained on IRC the rebar3_auto plugin is getting unloaded/purged upon calling rebar_agent:do(compile) thus killing the inotifywait process which it spawns.  You MUST NOT include {plugins, [rebar3_auto]}. inside the project local config file. To be clear only include {plugins, [rebar3_auto]}. in ~/.config/rebar3/rebar.config

**Comment by lrascao** [comment]
`rebar_prv_shell` already contains a blacklist of modules that is not allowed to touch, maybe rebar3 can expose an option that allows expanding that list

**Comment by drobakowski** [comment]
@vans163 thanks for sharing, this helped me a lot! 👍

**Comment by HaotaoYang** [comment]
@vans163 I can't find the directory in ~/.config/

**Comment by m-2k** [comment]
rebar.config: `{active,   ".*", {git, "git://github.com/synrc/active", {tag,"3.3"}}},`

console: `[ application:start(A) || A <- [fs,active]].`
